### ISSUE TITLE
Error when `fetch` is called with inline config object

### ISSUE THREAD

**Issue by ipavlovski** [jhmaster2000/bun-repl#13]
Keep getting the following error when running an `await fetch` command with a config object.

### Basic example:

```ts
await fetch('https://api.github.com/orgs/nodejs', { method: 'GET' }).then(v => v.json())
```
```
SyntaxError: Unexpected keyword 'return'. Expected '}' to end an object literal.
```

### When calling without config object, command runs just fine.

```ts
await fetch('https://api.github.com/orgs/nodejs').then(response => response.json())
```
```
{                                                                                                                                                                
  login: 'nodejs',                                                                                                                                               
  id: 9950313,                                                                                                                                                   
  node_id: 'MDEyOk9yZ2FuaXphdGlvbjk5NTAzMTM=',                                                                                                                   
  url: 'https://api.github.com/orgs/nodejs',                                                                                                                     
  repos_url: 'https://api.github.com/orgs/nodejs/repos',     
  // ...
}
```

### If the config object is declared prior, instead of declared inline - works fine too.
```ts
const config: FetchRequestInit = { method: 'GET'}
await fetch('https://api.github.com/orgs/nodejs', config).then(v => v.json())
```
```
{                                                                                                                                                                
  login: 'nodejs',                                                                                                                                               
  id: 9950313,                                                                                                                                                   
  node_id: 'MDEyOk9yZ2FuaXphdGlvbjk5NTAzMTM=',                                                                                                                   
  url: 'https://api.github.com/orgs/nodejs',                                                                                                                     
  repos_url: 'https://api.github.com/orgs/nodejs/repos',     
  // ...
}
```
---
Something about inline config definition is causing `SyntaxError: Unexpected keyword 'return'. Expected '}' to end an object literal`.

Thoughts?

**Comment by jhmaster2000** [comment]
This is caused by the precarious top-level await transpilation, the REPL doesn't \*really\* support TLA just yet, it only attempts to make a simple transform for now due to some constraints of the project, in order to allow *some* simple snippets to use TLA but it inevitably does fail for more complex things. The unexpected `return` you're seeing is coming from that TLA transformation, my assumption is that the inline object gets formatted across multiple lines which trips the TLA transform.

This will be naturally fixed eventually when TLA is just natively supported in the REPL runtime as it should be, but for now all you can do is be careful of your TLA usage in the REPL and try to find some workaround syntaxes like you did already.

Another way you could go about it for now is remove the `await` from the start, then you can run your code as-is with the inline object, and then await the underscore variable which holds the last REPL output value which in this case will be the promise to await: `await _;`

**Comment by ipavlovski** [comment]
That makes sense, thanks a lot for the elaboration.

**Good news**, is that workarounds are easy and only require minor refactoring.

**Bad news**, some libs won't work because of it.
E.g. was just testing out the new spotify typescript sdk (https://github.com/spotify/spotify-web-api-ts-sdk) and it kept tripping on the same error. 

Regardless, greatly appreciate the work on bun-repl.  👍 

Closing issue.
