### ISSUE TITLE
Implement `--version`

### ISSUE THREAD

**Issue by not-my-profile** [jhmaster2000/bun-repl#8]
I'd expect `bun repl --version` to print the version of this package.

**Comment by jhmaster2000** [comment]
Since it's planned to eventually be embedded directly into bun and no longer be independently versioned, the `--version` flag was phased out in 2.0.0, but in the next release you will be able to see the package version for debugging purposes again with `.info` inside the REPL (not in the current version)

**Comment by not-my-profile** [comment]
Thanks!
